users:
  - username: admin
    password: admin123
tenants:
  - name: config1
    user: "ocid1.user."
    tenancy: "ocid1.tenancy."
    fingerprint: "2"
    key_file: ""
    regions:
      - "us-phoenix-1"
  - name: config1
    user: "ocid1.user."
    tenancy: "ocid1.tenancy."
    fingerprint: "2"
    key_file: ""
    regions:
      - "us-phoenix-1"
