auth:
  users:
  - password: admin
    role: admin
    username: admin
app:
  secret_key: "your-secret-key-here"
security:
  max_login_attempts: 5
  lockout_duration: 300  # in seconds (5 minutes)

tenants:
- compartment_id: ocid1.tenancy.
  fingerprint: e0:fa:a8:be:c5
  key_file: c:\U
  name: 
  region: ap-chuncheon-1
  tenancy: ocid1.tenancy.
  user_ocid: ocid1.user.
- compartment_id: ocid1.tenancy.
  fingerprint: e0:fa:a8:b
  key_file: c:\Us
  name: 
  region: ap-sigapore-1
  tenancy: ocid1.tenancy.
  user_ocid: ocid1.user.
