app:
  secret_key: your-secret-key-here
auth:
  users:
  - mfa_enabled: false
    mfa_secret: null
    password: admin123
    role: admin
    username: admin
security:
  lockout_duration: 300
  max_login_attempts: 5
  mfa_issuer: OCI-Manager
